@startuml 线性代数1_2_1

' skinparam DefaultTextAlignment center

class 向量空间{
    --S--
    + V
    --operations--
    + 加法
    + 数乘
    --axioms--
    + 交换性:数乘无
    + 结合性
    + 单位元
    + 逆元:数乘无
    + 分配性
}

note left of 向量空间
V 是指任意集合.
一般当做Rn
end note

class 实向量空间{}
class 复向量空间{}

@enduml