@startuml mapping

class Mapping{
    + KN-ID: 主键
    + 关系
}

class AnkiKnowledge{
    + KN-ID:主键
}

class AnkiProblem{
    + PR-ID:主键
    + KN-IDs[]
    + PS-ID
}

class AnkiProcess{
    + PS-ID:主键
    + KN-IDs:[]
}

class AnkiErrorCase{
    + ER-ID: 主键
    + KN-IDs[]
    + PR-ID
    + PS-ID
}

@enduml